F = imread('C:\Image\mobil.png');
[tinggi, lebar] = size(F);
F2 = double(F);
for baris=2 : tinggi-1
for kolom=2 : lebar-1
jum = F2(baris-1, kolom-1)+ ...
F2(baris-1, kolom) + ...
F2(baris-1, kolom-1) + ...
F2(baris, kolom-1) + ...
F2(baris, kolom) + ...
F2(baris, kolom+1) + ...
F2(baris+1, kolom-1) + ...
F2(baris+1, kolom) + ...
F2(baris+1, kolom+1);
G(baris, kolom) = uint8(1/9 * jum);
end
end
figure(1); imshow(G);
clear;
